In [2]:
from __future__ import print_function
import numpy as np
import matplotlib.pyplot as plt
from time import time
from skimage import io


%matplotlib inline
plt.rcParams['figure.figsize'] = (10.0, 8.0) # set default size of plots
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'

%reload_ext autoreload



In [7]:
eigenvalues = []
eigenvectors = []
M=np.array(range(10)).reshape((2,5))
print(M)
w, v = np.linalg.eig(M)
### YOUR CODE HERE
#w, v=eigen_decomp(M)
#eigenvalues=w[:k]

[[0 1 2 3 4]
 [5 6 7 8 9]]


LinAlgError: Last 2 dimensions of the array must be square

In [4]:
def eigen_decomp(M):
    """Implement eigenvalue decomposition.

    (optional): You might find the `np.linalg.eig` function useful.

    Args:
        matrix: numpy matrix of shape (m, n)

    Returns:
        w: numpy array of shape (m, m) such that the column v[:,i] is the eigenvector corresponding to the eigenvalue w[i].
        v: Matrix where every column is an eigenvector.
    """
    w = None
    v = None
    ### YOUR CODE HERE
    w, v = np.linalg.eig(M)
    ### END YOUR CODE
    return w, v

In [14]:
array = np.array(range(16)).reshape((4,4))
output= array>10
print(output)
array[output]

[[False False False False]
 [False False False False]
 [False False False  True]
 [ True  True  True  True]]


array([11, 12, 13, 14, 15])

In [18]:
array=np.linspace(1,10,10)
array
dup=array[:]
dup
print(id(dup))
print(id(array))

2871638045008
2871636800976
